-- 1 Media Solution: lead storage
-- Run this once in Supabase > SQL Editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  form_type text not null default 'contact',
  full_name text not null,
  email text not null,
  whatsapp text not null,
  company_name text not null,
  website_url text,
  objective text not null,
  budget text,
  notes text,
  source_url text,
  user_agent text
);

alter table public.leads enable row level security;

-- No public/browser policy is created.
-- Only the Vercel server function uses the service-role key.
